name: docker-sync
services:
  test:
    build: .
    image: docker-sync
    container_name: docker-sync-test
    volumes:
      - ./test:/from
      - test:/to
    environment:
      DOCKER_SYNC_IGNORED: ""
volumes:
  test:
